export const SET_PRODUCTS = "SET_PRODUCTS";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_PRODUCT_LOADING = "SET_PRODUCT_LOADING";
